INSERT INTO ROLES(ID,NAME)VALUES(1,'ROLE_USER')
INSERT INTO ROLES(ID,NAME)VALUES(2,'ROLE_MODERATOR')
INSERT INTO ROLES(ID,NAME)VALUES(3,'ROLE_ADMIN')

INSERT INTO AUTHORITY(NAME)VALUES(0)
INSERT INTO AUTHORITY(NAME)VALUES(1)
INSERT INTO AUTHORITY(NAME)VALUES(2)
INSERT INTO AUTHORITY(NAME)VALUES(3)